In [1]:
import torch

In [4]:
torch.empty(5,3)

tensor([[9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38]])

In [5]:
torch.rand(5,3)

tensor([[0.7365, 0.3397, 0.2794],
        [0.2225, 0.4231, 0.6324],
        [0.0670, 0.7608, 0.5423],
        [0.1288, 0.4098, 0.7056],
        [0.8377, 0.5425, 0.9973]])

In [6]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.zeros(5,3)

In [8]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x.dtype

torch.float32

In [11]:
x=torch.zeros(5,3,dtype=torch.long)

In [14]:
x = torch.tensor([5.5,3])

In [15]:
x

tensor([5.5000, 3.0000])

In [16]:
x = x.mew_ones(5,3,dtype=torch.double)

AttributeError: 'Tensor' object has no attribute 'mew_ones'

In [17]:
x = x.new_ones(5,3,dtype=torch.double)

In [18]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
y=torch.rand(5,3)

In [20]:
y

tensor([[0.5508, 0.7080, 0.1447],
        [0.2817, 0.9519, 0.3263],
        [0.5016, 0.8813, 0.8704],
        [0.5195, 0.8744, 0.1299],
        [0.9366, 0.2603, 0.9398]])

In [21]:
x + y

RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float

In [40]:
import numpy as np
import torch

def fizz_buzz_encode(i):
    if i % 15 == 0:return 3
    elif i % 5 == 0:return 2
    elif i % 3 == 0:return 1
    else: return 0
    
def fizz_buzz_decode(i, prediction):
    return [str(i), "fizz","buzz","fizzbuzz"][prediction]

def helper(i):
    print(fizz_buzz_decode(i,fizz_buzz_encode(i)))

for i in range(1,16):
    helper(i)

NUM_DIGITS = 10

def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])[::-1]

trX = torch.Tensor([binary_encode(i,NUM_DIGITS) for i in range(101,2**NUM_DIGITS)])
trY = torch.LongTensor([fizz_buzz_encode(i) for i in range(101,2**NUM_DIGITS)])

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz


In [30]:
trX.shape
trY.shape

torch.Size([923])

In [37]:
NUM_HIDDEN = 100
model = torch.nn.Sequential(
    torch.nn.Linear(NUM_DIGITS,NUM_HIDDEN),
    torch.nn.ReLU(),
    torch.nn.Linear(NUM_HIDDEN,4)
)
if torch.cuda.is_available():
    model = model.cuda()


In [43]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.5)

In [36]:
BATCH_SIZE = 128

In [44]:
for epoch in range(1000):
    for start in range(0,len(trX),BATCH_SIZE):
        end = start + BATCH_SIZE
        batchX = trX[start:end]
        batchY = trY[start:end]
        if torch.cuda.is_available():
            batchX = batchX.cuda()
            batchY = batchY.cuda()
        y_pred = model(batchX)
        loss = loss_fn(y_pred,batchY)
        print("Epoch",epoch,loss.item())
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

Epoch 0 1.3072715997695923
Epoch 0 28.44175910949707
Epoch 0 13.525510787963867
Epoch 0 1.2415932416915894
Epoch 0 1.2105070352554321
Epoch 0 1.1773886680603027
Epoch 0 1.1591734886169434
Epoch 0 1.1413339376449585
Epoch 1 1.1757760047912598
Epoch 1 1.2721161842346191
Epoch 1 1.2000471353530884
Epoch 1 1.269972562789917
Epoch 1 1.1807076930999756
Epoch 1 1.1902744770050049
Epoch 1 1.152430534362793
Epoch 1 1.1148536205291748
Epoch 2 1.1348479986190796
Epoch 2 1.1483322381973267
Epoch 2 1.1528793573379517
Epoch 2 1.1635584831237793
Epoch 2 1.1653785705566406
Epoch 2 1.1495068073272705
Epoch 2 1.154096245765686
Epoch 2 1.1236132383346558
Epoch 3 1.133019208908081
Epoch 3 1.1402231454849243
Epoch 3 1.1365008354187012
Epoch 3 1.156153678894043
Epoch 3 1.146904706954956
Epoch 3 1.143674612045288
Epoch 3 1.1507898569107056
Epoch 3 1.1186566352844238
Epoch 4 1.1343744993209839
Epoch 4 1.1385833024978638
Epoch 4 1.1339069604873657
Epoch 4 1.1447782516479492
Epoch 4 1.1410417556762695
Epoch 4 1

Epoch 38 1.1325255632400513
Epoch 38 1.1386874914169312
Epoch 38 1.132116436958313
Epoch 38 1.1461725234985352
Epoch 38 1.1377928256988525
Epoch 38 1.1323339939117432
Epoch 38 1.143423080444336
Epoch 38 1.1201602220535278
Epoch 39 1.1325335502624512
Epoch 39 1.1387147903442383
Epoch 39 1.1321462392807007
Epoch 39 1.1462558507919312
Epoch 39 1.1377965211868286
Epoch 39 1.1323305368423462
Epoch 39 1.14345383644104
Epoch 39 1.1202740669250488
Epoch 40 1.1325405836105347
Epoch 40 1.1387430429458618
Epoch 40 1.1321779489517212
Epoch 40 1.1463396549224854
Epoch 40 1.137799620628357
Epoch 40 1.1323277950286865
Epoch 40 1.143486738204956
Epoch 40 1.1203874349594116
Epoch 41 1.132547378540039
Epoch 41 1.1387724876403809
Epoch 41 1.132212519645691
Epoch 41 1.146423578262329
Epoch 41 1.1378024816513062
Epoch 41 1.132325530052185
Epoch 41 1.1435215473175049
Epoch 41 1.1205002069473267
Epoch 42 1.1325531005859375
Epoch 42 1.1388028860092163
Epoch 42 1.132248878479004
Epoch 42 1.1465078592300415
Epo

Epoch 75 1.1334340572357178
Epoch 75 1.1457595825195312
Epoch 75 1.1222487688064575
Epoch 76 1.1324591636657715
Epoch 76 1.1415321826934814
Epoch 76 1.1346052885055542
Epoch 76 1.1478331089019775
Epoch 76 1.138079285621643
Epoch 76 1.1335116624832153
Epoch 76 1.1458079814910889
Epoch 76 1.1221940517425537
Epoch 77 1.132479190826416
Epoch 77 1.1416558027267456
Epoch 77 1.1346509456634521
Epoch 77 1.1477866172790527
Epoch 77 1.1381250619888306
Epoch 77 1.1335893869400024
Epoch 77 1.145851492881775
Epoch 77 1.1221349239349365
Epoch 78 1.1325021982192993
Epoch 78 1.1417783498764038
Epoch 78 1.1346913576126099
Epoch 78 1.1477365493774414
Epoch 78 1.138174295425415
Epoch 78 1.1336671113967896
Epoch 78 1.145890235900879
Epoch 78 1.122071385383606
Epoch 79 1.1325286626815796
Epoch 79 1.1418993473052979
Epoch 79 1.1347261667251587
Epoch 79 1.1476829051971436
Epoch 79 1.1382267475128174
Epoch 79 1.133744239807129
Epoch 79 1.1459239721298218
Epoch 79 1.1220041513442993
Epoch 80 1.1325583457946777

Epoch 112 1.145153522491455
Epoch 112 1.1197562217712402
Epoch 113 1.1343333721160889
Epoch 113 1.143910527229309
Epoch 113 1.133780598640442
Epoch 113 1.1458462476730347
Epoch 113 1.140829086303711
Epoch 113 1.134963870048523
Epoch 113 1.1451056003570557
Epoch 113 1.1197134256362915
Epoch 114 1.1343848705291748
Epoch 114 1.1439064741134644
Epoch 114 1.1337261199951172
Epoch 114 1.1458156108856201
Epoch 114 1.1408991813659668
Epoch 114 1.1349539756774902
Epoch 114 1.1450581550598145
Epoch 114 1.1196719408035278
Epoch 115 1.1344352960586548
Epoch 115 1.1438995599746704
Epoch 115 1.1336716413497925
Epoch 115 1.1457868814468384
Epoch 115 1.1409674882888794
Epoch 115 1.1349422931671143
Epoch 115 1.1450105905532837
Epoch 115 1.1196324825286865
Epoch 116 1.1344844102859497
Epoch 116 1.1438897848129272
Epoch 116 1.1336174011230469
Epoch 116 1.1457598209381104
Epoch 116 1.1410340070724487
Epoch 116 1.1349281072616577
Epoch 116 1.144963026046753
Epoch 116 1.1195950508117676
Epoch 117 1.13453221

Epoch 149 1.1351569890975952
Epoch 149 1.1423394680023193
Epoch 149 1.1322290897369385
Epoch 149 1.14559006690979
Epoch 149 1.1420080661773682
Epoch 149 1.1336530447006226
Epoch 149 1.143854022026062
Epoch 149 1.1191527843475342
Epoch 150 1.1351442337036133
Epoch 150 1.1422703266143799
Epoch 150 1.1322072744369507
Epoch 150 1.1455990076065063
Epoch 150 1.1419950723648071
Epoch 150 1.1336036920547485
Epoch 150 1.1438409090042114
Epoch 150 1.119156002998352
Epoch 151 1.135129690170288
Epoch 151 1.1422009468078613
Epoch 151 1.1321872472763062
Epoch 151 1.1456081867218018
Epoch 151 1.1419792175292969
Epoch 151 1.1335545778274536
Epoch 151 1.1438294649124146
Epoch 151 1.119160532951355
Epoch 152 1.1351135969161987
Epoch 152 1.1421315670013428
Epoch 152 1.1321682929992676
Epoch 152 1.1456174850463867
Epoch 152 1.1419614553451538
Epoch 152 1.1335058212280273
Epoch 152 1.1438194513320923
Epoch 152 1.1191654205322266
Epoch 153 1.1350957155227661
Epoch 153 1.1420625448226929
Epoch 153 1.13215112

Epoch 185 1.134078860282898
Epoch 185 1.1403367519378662
Epoch 185 1.1320955753326416
Epoch 185 1.1458553075790405
Epoch 185 1.1406866312026978
Epoch 185 1.1324541568756104
Epoch 185 1.1439294815063477
Epoch 185 1.1194336414337158
Epoch 186 1.1340467929840088
Epoch 186 1.1403040885925293
Epoch 186 1.1321016550064087
Epoch 186 1.145858883857727
Epoch 186 1.1406457424163818
Epoch 186 1.1324405670166016
Epoch 186 1.1439378261566162
Epoch 186 1.1194427013397217
Epoch 187 1.1340152025222778
Epoch 187 1.140273094177246
Epoch 187 1.1321074962615967
Epoch 187 1.145862340927124
Epoch 187 1.140605092048645
Epoch 187 1.1324280500411987
Epoch 187 1.1439458131790161
Epoch 187 1.119451642036438
Epoch 188 1.1339846849441528
Epoch 188 1.1402428150177002
Epoch 188 1.1321134567260742
Epoch 188 1.1458659172058105
Epoch 188 1.1405653953552246
Epoch 188 1.1324162483215332
Epoch 188 1.1439536809921265
Epoch 188 1.1194605827331543
Epoch 189 1.1339542865753174
Epoch 189 1.1402138471603394
Epoch 189 1.13211953

Epoch 220 1.119746208190918
Epoch 221 1.1332776546478271
Epoch 221 1.1397145986557007
Epoch 221 1.1322808265686035
Epoch 221 1.145951509475708
Epoch 221 1.1396253108978271
Epoch 221 1.1323063373565674
Epoch 221 1.1441419124603271
Epoch 221 1.1197545528411865
Epoch 222 1.1332639455795288
Epoch 222 1.1397075653076172
Epoch 222 1.1322842836380005
Epoch 222 1.145953893661499
Epoch 222 1.1396067142486572
Epoch 222 1.1323072910308838
Epoch 222 1.1441452503204346
Epoch 222 1.119762897491455
Epoch 223 1.1332508325576782
Epoch 223 1.1397007703781128
Epoch 223 1.1322877407073975
Epoch 223 1.1459559202194214
Epoch 223 1.1395885944366455
Epoch 223 1.1323087215423584
Epoch 223 1.144148588180542
Epoch 223 1.119771122932434
Epoch 224 1.1332380771636963
Epoch 224 1.139694333076477
Epoch 224 1.132291316986084
Epoch 224 1.145958423614502
Epoch 224 1.1395708322525024
Epoch 224 1.1323102712631226
Epoch 224 1.1441518068313599
Epoch 224 1.1197797060012817
Epoch 225 1.1332255601882935
Epoch 225 1.13968813419

Epoch 257 1.1323988437652588
Epoch 257 1.1442235708236694
Epoch 257 1.1200239658355713
Epoch 258 1.1329493522644043
Epoch 258 1.139589548110962
Epoch 258 1.1323789358139038
Epoch 258 1.146033525466919
Epoch 258 1.1391608715057373
Epoch 258 1.1324020624160767
Epoch 258 1.1442251205444336
Epoch 258 1.1200305223464966
Epoch 259 1.132943868637085
Epoch 259 1.1395885944366455
Epoch 259 1.1323808431625366
Epoch 259 1.1460354328155518
Epoch 259 1.1391527652740479
Epoch 259 1.1324056386947632
Epoch 259 1.1442261934280396
Epoch 259 1.1200367212295532
Epoch 260 1.1329383850097656
Epoch 260 1.1395877599716187
Epoch 260 1.1323826313018799
Epoch 260 1.1460373401641846
Epoch 260 1.1391448974609375
Epoch 260 1.1324090957641602
Epoch 260 1.144228219985962
Epoch 260 1.120043396949768
Epoch 261 1.1329333782196045
Epoch 261 1.1395866870880127
Epoch 261 1.1323845386505127
Epoch 261 1.146039605140686
Epoch 261 1.1391373872756958
Epoch 261 1.1324125528335571
Epoch 261 1.1442294120788574
Epoch 261 1.12004983

Epoch 293 1.1325371265411377
Epoch 293 1.1442677974700928
Epoch 293 1.1202292442321777
Epoch 294 1.1328080892562866
Epoch 294 1.1395972967147827
Epoch 294 1.1324410438537598
Epoch 294 1.146096110343933
Epoch 294 1.138947606086731
Epoch 294 1.132541298866272
Epoch 294 1.1442691087722778
Epoch 294 1.1202343702316284
Epoch 295 1.1328054666519165
Epoch 295 1.1395983695983887
Epoch 295 1.1324424743652344
Epoch 295 1.1460976600646973
Epoch 295 1.1389431953430176
Epoch 295 1.1325455904006958
Epoch 295 1.144270420074463
Epoch 295 1.1202391386032104
Epoch 296 1.1328027248382568
Epoch 296 1.139599323272705
Epoch 296 1.1324442625045776
Epoch 296 1.1460989713668823
Epoch 296 1.1389389038085938
Epoch 296 1.1325498819351196
Epoch 296 1.1442712545394897
Epoch 296 1.1202439069747925
Epoch 297 1.1328001022338867
Epoch 297 1.1396006345748901
Epoch 297 1.1324458122253418
Epoch 297 1.1461002826690674
Epoch 297 1.1389347314834595
Epoch 297 1.132554292678833
Epoch 297 1.1442723274230957
Epoch 297 1.12024867

Epoch 329 1.12037992477417
Epoch 330 1.1327358484268188
Epoch 330 1.1396621465682983
Epoch 330 1.1324963569641113
Epoch 330 1.1461338996887207
Epoch 330 1.138817548751831
Epoch 330 1.1327153444290161
Epoch 330 1.144309401512146
Epoch 330 1.1203831434249878
Epoch 331 1.1327345371246338
Epoch 331 1.1396644115447998
Epoch 331 1.132498025894165
Epoch 331 1.1461344957351685
Epoch 331 1.1388144493103027
Epoch 331 1.1327208280563354
Epoch 331 1.1443103551864624
Epoch 331 1.1203866004943848
Epoch 332 1.1327332258224487
Epoch 332 1.13966703414917
Epoch 332 1.1324994564056396
Epoch 332 1.1461353302001953
Epoch 332 1.1388113498687744
Epoch 332 1.1327263116836548
Epoch 332 1.1443116664886475
Epoch 332 1.1203895807266235
Epoch 333 1.1327316761016846
Epoch 333 1.13966965675354
Epoch 333 1.1325011253356934
Epoch 333 1.1461358070373535
Epoch 333 1.1388084888458252
Epoch 333 1.132731556892395
Epoch 333 1.1443127393722534
Epoch 333 1.120392918586731
Epoch 334 1.132730484008789
Epoch 334 1.13967204093933

Epoch 366 1.146136999130249
Epoch 366 1.1387182474136353
Epoch 366 1.1329306364059448
Epoch 366 1.1443474292755127
Epoch 366 1.1204699277877808
Epoch 367 1.132703185081482
Epoch 367 1.1397744417190552
Epoch 367 1.1325472593307495
Epoch 367 1.1461366415023804
Epoch 367 1.1387157440185547
Epoch 367 1.1329373121261597
Epoch 367 1.1443485021591187
Epoch 367 1.1204712390899658
Epoch 368 1.132703185081482
Epoch 368 1.1397778987884521
Epoch 368 1.1325485706329346
Epoch 368 1.1461362838745117
Epoch 368 1.1387133598327637
Epoch 368 1.1329439878463745
Epoch 368 1.1443493366241455
Epoch 368 1.12047278881073
Epoch 369 1.1327028274536133
Epoch 369 1.1397815942764282
Epoch 369 1.1325496435165405
Epoch 369 1.146135687828064
Epoch 369 1.1387109756469727
Epoch 369 1.1329504251480103
Epoch 369 1.1443504095077515
Epoch 369 1.1204739809036255
Epoch 370 1.132702350616455
Epoch 370 1.1397852897644043
Epoch 370 1.1325513124465942
Epoch 370 1.1461352109909058
Epoch 370 1.1387083530426025
Epoch 370 1.132957100

Epoch 402 1.1460976600646973
Epoch 402 1.1386406421661377
Epoch 402 1.1331868171691895
Epoch 402 1.1443777084350586
Epoch 402 1.120482325553894
Epoch 403 1.1327059268951416
Epoch 403 1.139927864074707
Epoch 403 1.1325886249542236
Epoch 403 1.1460962295532227
Epoch 403 1.1386384963989258
Epoch 403 1.133194923400879
Epoch 403 1.1443780660629272
Epoch 403 1.1204816102981567
Epoch 404 1.1327062845230103
Epoch 404 1.1399327516555786
Epoch 404 1.1325901746749878
Epoch 404 1.1460944414138794
Epoch 404 1.138636827468872
Epoch 404 1.1332024335861206
Epoch 404 1.144378662109375
Epoch 404 1.1204807758331299
Epoch 405 1.1327067613601685
Epoch 405 1.1399377584457397
Epoch 405 1.1325907707214355
Epoch 405 1.146092414855957
Epoch 405 1.1386350393295288
Epoch 405 1.1332101821899414
Epoch 405 1.1443793773651123
Epoch 405 1.1204794645309448
Epoch 406 1.1327075958251953
Epoch 406 1.1399427652359009
Epoch 406 1.1325920820236206
Epoch 406 1.146091103553772
Epoch 406 1.138633370399475
Epoch 406 1.1332176923

Epoch 438 1.1327344179153442
Epoch 438 1.1401214599609375
Epoch 438 1.1326286792755127
Epoch 438 1.1460163593292236
Epoch 438 1.1385880708694458
Epoch 438 1.1334768533706665
Epoch 438 1.1443982124328613
Epoch 438 1.1204169988632202
Epoch 439 1.1327353715896606
Epoch 439 1.1401275396347046
Epoch 439 1.132629632949829
Epoch 439 1.1460137367248535
Epoch 439 1.1385871171951294
Epoch 439 1.1334850788116455
Epoch 439 1.1443986892700195
Epoch 439 1.120414137840271
Epoch 440 1.1327365636825562
Epoch 440 1.1401337385177612
Epoch 440 1.1326310634613037
Epoch 440 1.1460107564926147
Epoch 440 1.138586163520813
Epoch 440 1.1334935426712036
Epoch 440 1.1443995237350464
Epoch 440 1.1204113960266113
Epoch 441 1.132737636566162
Epoch 441 1.1401398181915283
Epoch 441 1.1326323747634888
Epoch 441 1.1460078954696655
Epoch 441 1.138584852218628
Epoch 441 1.1335018873214722
Epoch 441 1.1443997621536255
Epoch 441 1.120408535003662
Epoch 442 1.1327388286590576
Epoch 442 1.1401461362838745
Epoch 442 1.13263356

Epoch 474 1.145907998085022
Epoch 474 1.1385622024536133
Epoch 474 1.1337755918502808
Epoch 474 1.144415259361267
Epoch 474 1.1202950477600098
Epoch 475 1.1327776908874512
Epoch 475 1.1403594017028809
Epoch 475 1.1326801776885986
Epoch 475 1.145904779434204
Epoch 475 1.138561725616455
Epoch 475 1.1337835788726807
Epoch 475 1.1444156169891357
Epoch 475 1.1202915906906128
Epoch 476 1.132778525352478
Epoch 476 1.1403659582138062
Epoch 476 1.1326818466186523
Epoch 476 1.1459015607833862
Epoch 476 1.1385612487792969
Epoch 476 1.1337913274765015
Epoch 476 1.144416332244873
Epoch 476 1.1202874183654785
Epoch 477 1.132779836654663
Epoch 477 1.1403725147247314
Epoch 477 1.132683515548706
Epoch 477 1.145898461341858
Epoch 477 1.1385608911514282
Epoch 477 1.1337991952896118
Epoch 477 1.1444168090820312
Epoch 477 1.1202837228775024
Epoch 478 1.1327810287475586
Epoch 478 1.1403789520263672
Epoch 478 1.1326851844787598
Epoch 478 1.14589524269104
Epoch 478 1.1385605335235596
Epoch 478 1.1338073015213

Epoch 510 1.120160460472107
Epoch 511 1.132812261581421
Epoch 511 1.1405808925628662
Epoch 511 1.1327414512634277
Epoch 511 1.1457977294921875
Epoch 511 1.138553261756897
Epoch 511 1.1340446472167969
Epoch 511 1.1444350481033325
Epoch 511 1.1201566457748413
Epoch 512 1.1328130960464478
Epoch 512 1.1405866146087646
Epoch 512 1.132743000984192
Epoch 512 1.145795226097107
Epoch 512 1.1385531425476074
Epoch 512 1.134050726890564
Epoch 512 1.1444355249404907
Epoch 512 1.1201534271240234
Epoch 513 1.1328139305114746
Epoch 513 1.1405918598175049
Epoch 513 1.1327450275421143
Epoch 513 1.1457924842834473
Epoch 513 1.1385530233383179
Epoch 513 1.1340569257736206
Epoch 513 1.144436001777649
Epoch 513 1.1201494932174683
Epoch 514 1.1328145265579224
Epoch 514 1.1405972242355347
Epoch 514 1.132746696472168
Epoch 514 1.145789623260498
Epoch 514 1.1385527849197388
Epoch 514 1.1340630054473877
Epoch 514 1.1444367170333862
Epoch 514 1.120146632194519
Epoch 515 1.1328152418136597
Epoch 515 1.140602946281

Epoch 546 1.144454002380371
Epoch 546 1.120052456855774
Epoch 547 1.1328275203704834
Epoch 547 1.1407443284988403
Epoch 547 1.1328011751174927
Epoch 547 1.1457158327102661
Epoch 547 1.1385488510131836
Epoch 547 1.1342289447784424
Epoch 547 1.1444544792175293
Epoch 547 1.1200501918792725
Epoch 548 1.1328277587890625
Epoch 548 1.1407480239868164
Epoch 548 1.1328026056289673
Epoch 548 1.1457140445709229
Epoch 548 1.138548731803894
Epoch 548 1.1342328786849976
Epoch 548 1.1444549560546875
Epoch 548 1.1200475692749023
Epoch 549 1.1328277587890625
Epoch 549 1.1407512426376343
Epoch 549 1.1328039169311523
Epoch 549 1.14571213722229
Epoch 549 1.1385486125946045
Epoch 549 1.1342365741729736
Epoch 549 1.1444556713104248
Epoch 549 1.1200453042984009
Epoch 550 1.1328277587890625
Epoch 550 1.1407546997070312
Epoch 550 1.132805585861206
Epoch 550 1.1457104682922363
Epoch 550 1.1385483741760254
Epoch 550 1.1342406272888184
Epoch 550 1.144455909729004
Epoch 550 1.1200425624847412
Epoch 551 1.132828116

Epoch 582 1.144467830657959
Epoch 582 1.1199856996536255
Epoch 583 1.1328245401382446
Epoch 583 1.1408313512802124
Epoch 583 1.1328456401824951
Epoch 583 1.1456650495529175
Epoch 583 1.1385436058044434
Epoch 583 1.1343287229537964
Epoch 583 1.144468069076538
Epoch 583 1.1199843883514404
Epoch 584 1.132824182510376
Epoch 584 1.1408330202102661
Epoch 584 1.1328465938568115
Epoch 584 1.145664095878601
Epoch 584 1.1385436058044434
Epoch 584 1.1343302726745605
Epoch 584 1.1444685459136963
Epoch 584 1.1199830770492554
Epoch 585 1.1328243017196655
Epoch 585 1.140834093093872
Epoch 585 1.1328473091125488
Epoch 585 1.1456632614135742
Epoch 585 1.1385434865951538
Epoch 585 1.1343320608139038
Epoch 585 1.1444685459136963
Epoch 585 1.1199818849563599
Epoch 586 1.1328238248825073
Epoch 586 1.1408356428146362
Epoch 586 1.1328482627868652
Epoch 586 1.1456623077392578
Epoch 586 1.1385432481765747
Epoch 586 1.1343334913253784
Epoch 586 1.1444690227508545
Epoch 586 1.1199805736541748
Epoch 587 1.1328234

Epoch 619 1.1328691244125366
Epoch 619 1.1456384658813477
Epoch 619 1.1385390758514404
Epoch 619 1.1343650817871094
Epoch 619 1.1444727182388306
Epoch 619 1.1199511289596558
Epoch 620 1.132813572883606
Epoch 620 1.1408580541610718
Epoch 620 1.1328694820404053
Epoch 620 1.1456378698349
Epoch 620 1.1385388374328613
Epoch 620 1.1343653202056885
Epoch 620 1.1444729566574097
Epoch 620 1.1199506521224976
Epoch 621 1.1328133344650269
Epoch 621 1.1408580541610718
Epoch 621 1.1328699588775635
Epoch 621 1.1456376314163208
Epoch 621 1.1385387182235718
Epoch 621 1.1343659162521362
Epoch 621 1.1444729566574097
Epoch 621 1.119950532913208
Epoch 622 1.1328130960464478
Epoch 622 1.1408584117889404
Epoch 622 1.1328703165054321
Epoch 622 1.1456373929977417
Epoch 622 1.1385383605957031
Epoch 622 1.1343661546707153
Epoch 622 1.1444728374481201
Epoch 622 1.1199499368667603
Epoch 623 1.1328126192092896
Epoch 623 1.1408584117889404
Epoch 623 1.1328707933425903
Epoch 623 1.145636796951294
Epoch 623 1.13853859

Epoch 655 1.1328766345977783
Epoch 655 1.145626187324524
Epoch 655 1.1385356187820435
Epoch 655 1.1343679428100586
Epoch 655 1.1444706916809082
Epoch 655 1.1199376583099365
Epoch 656 1.1328033208847046
Epoch 656 1.140852451324463
Epoch 656 1.1328765153884888
Epoch 656 1.1456263065338135
Epoch 656 1.1385358572006226
Epoch 656 1.1343677043914795
Epoch 656 1.14447021484375
Epoch 656 1.119937777519226
Epoch 657 1.132803201675415
Epoch 657 1.1408517360687256
Epoch 657 1.1328765153884888
Epoch 657 1.1456255912780762
Epoch 657 1.1385356187820435
Epoch 657 1.13436758518219
Epoch 657 1.1444703340530396
Epoch 657 1.1199373006820679
Epoch 658 1.132802963256836
Epoch 658 1.140851616859436
Epoch 658 1.1328768730163574
Epoch 658 1.1456258296966553
Epoch 658 1.1385356187820435
Epoch 658 1.1343672275543213
Epoch 658 1.1444703340530396
Epoch 658 1.1199370622634888
Epoch 659 1.1328027248382568
Epoch 659 1.1408509016036987
Epoch 659 1.1328768730163574
Epoch 659 1.1456254720687866
Epoch 659 1.138535499572

Epoch 690 1.1199336051940918
Epoch 691 1.1327968835830688
Epoch 691 1.1408371925354004
Epoch 691 1.1328750848770142
Epoch 691 1.1456209421157837
Epoch 691 1.1385345458984375
Epoch 691 1.1343587636947632
Epoch 691 1.1444652080535889
Epoch 691 1.1199336051940918
Epoch 692 1.1327968835830688
Epoch 692 1.1408369541168213
Epoch 692 1.1328747272491455
Epoch 692 1.1456208229064941
Epoch 692 1.138534665107727
Epoch 692 1.1343586444854736
Epoch 692 1.144465446472168
Epoch 692 1.1199332475662231
Epoch 693 1.1327968835830688
Epoch 693 1.1408363580703735
Epoch 693 1.132874846458435
Epoch 693 1.1456209421157837
Epoch 693 1.1385345458984375
Epoch 693 1.134358286857605
Epoch 693 1.1444647312164307
Epoch 693 1.1199332475662231
Epoch 694 1.1327964067459106
Epoch 694 1.1408361196517944
Epoch 694 1.132874846458435
Epoch 694 1.1456208229064941
Epoch 694 1.138534665107727
Epoch 694 1.1343581676483154
Epoch 694 1.1444650888442993
Epoch 694 1.1199333667755127
Epoch 695 1.1327965259552002
Epoch 695 1.14083528

Epoch 726 1.1444605588912964
Epoch 726 1.1199324131011963
Epoch 727 1.13279390335083
Epoch 727 1.1408239603042603
Epoch 727 1.1328709125518799
Epoch 727 1.1456187963485718
Epoch 727 1.138534665107727
Epoch 727 1.1343498229980469
Epoch 727 1.1444603204727173
Epoch 727 1.1199322938919067
Epoch 728 1.13279390335083
Epoch 728 1.1408236026763916
Epoch 728 1.1328704357147217
Epoch 728 1.1456189155578613
Epoch 728 1.1385345458984375
Epoch 728 1.1343495845794678
Epoch 728 1.1444603204727173
Epoch 728 1.1199326515197754
Epoch 729 1.1327940225601196
Epoch 729 1.140823245048523
Epoch 729 1.132870078086853
Epoch 729 1.1456185579299927
Epoch 729 1.1385345458984375
Epoch 729 1.1343493461608887
Epoch 729 1.1444600820541382
Epoch 729 1.1199324131011963
Epoch 730 1.132793664932251
Epoch 730 1.1408230066299438
Epoch 730 1.1328701972961426
Epoch 730 1.1456187963485718
Epoch 730 1.1385345458984375
Epoch 730 1.13434898853302
Epoch 730 1.1444599628448486
Epoch 730 1.1199320554733276
Epoch 731 1.132793784141

Epoch 763 1.1408158540725708
Epoch 763 1.132866621017456
Epoch 763 1.1456178426742554
Epoch 763 1.1385349035263062
Epoch 763 1.134344220161438
Epoch 763 1.1444569826126099
Epoch 763 1.1199322938919067
Epoch 764 1.1327931880950928
Epoch 764 1.1408156156539917
Epoch 764 1.1328665018081665
Epoch 764 1.1456178426742554
Epoch 764 1.1385351419448853
Epoch 764 1.1343441009521484
Epoch 764 1.1444568634033203
Epoch 764 1.1199322938919067
Epoch 765 1.1327931880950928
Epoch 765 1.140815258026123
Epoch 765 1.132866382598877
Epoch 765 1.1456178426742554
Epoch 765 1.1385352611541748
Epoch 765 1.1343439817428589
Epoch 765 1.1444565057754517
Epoch 765 1.1199320554733276
Epoch 766 1.1327931880950928
Epoch 766 1.1408151388168335
Epoch 766 1.132866382598877
Epoch 766 1.1456178426742554
Epoch 766 1.1385352611541748
Epoch 766 1.1343438625335693
Epoch 766 1.1444566249847412
Epoch 766 1.1199320554733276
Epoch 767 1.1327933073043823
Epoch 767 1.1408147811889648
Epoch 767 1.1328662633895874
Epoch 767 1.1456176

Epoch 799 1.145617127418518
Epoch 799 1.1385356187820435
Epoch 799 1.1343424320220947
Epoch 799 1.1444547176361084
Epoch 799 1.119931697845459
Epoch 800 1.1327935457229614
Epoch 800 1.1408121585845947
Epoch 800 1.1328641176223755
Epoch 800 1.145617127418518
Epoch 800 1.1385356187820435
Epoch 800 1.1343423128128052
Epoch 800 1.1444545984268188
Epoch 800 1.119931697845459
Epoch 801 1.1327935457229614
Epoch 801 1.1408121585845947
Epoch 801 1.132864236831665
Epoch 801 1.145617127418518
Epoch 801 1.138535976409912
Epoch 801 1.1343423128128052
Epoch 801 1.1444549560546875
Epoch 801 1.1199315786361694
Epoch 802 1.1327935457229614
Epoch 802 1.1408122777938843
Epoch 802 1.1328637599945068
Epoch 802 1.1456172466278076
Epoch 802 1.138535737991333
Epoch 802 1.1343424320220947
Epoch 802 1.1444547176361084
Epoch 802 1.1199315786361694
Epoch 803 1.1327937841415405
Epoch 803 1.1408121585845947
Epoch 803 1.1328637599945068
Epoch 803 1.145617127418518
Epoch 803 1.1385358572006226
Epoch 803 1.13434231281

Epoch 835 1.13286292552948
Epoch 835 1.1456162929534912
Epoch 835 1.1385362148284912
Epoch 835 1.1343427896499634
Epoch 835 1.144454002380371
Epoch 835 1.1199309825897217
Epoch 836 1.1327944993972778
Epoch 836 1.1408121585845947
Epoch 836 1.1328630447387695
Epoch 836 1.1456162929534912
Epoch 836 1.1385363340377808
Epoch 836 1.134342908859253
Epoch 836 1.144453763961792
Epoch 836 1.1199311017990112
Epoch 837 1.1327944993972778
Epoch 837 1.1408122777938843
Epoch 837 1.13286292552948
Epoch 837 1.1456162929534912
Epoch 837 1.1385362148284912
Epoch 837 1.1343430280685425
Epoch 837 1.144453763961792
Epoch 837 1.1199311017990112
Epoch 838 1.1327944993972778
Epoch 838 1.1408122777938843
Epoch 838 1.13286292552948
Epoch 838 1.1456162929534912
Epoch 838 1.1385363340377808
Epoch 838 1.1343430280685425
Epoch 838 1.144453763961792
Epoch 838 1.1199313402175903
Epoch 839 1.1327943801879883
Epoch 839 1.1408122777938843
Epoch 839 1.13286292552948
Epoch 839 1.1456164121627808
Epoch 839 1.138536334037780

Epoch 871 1.145615577697754
Epoch 871 1.1385362148284912
Epoch 871 1.1343443393707275
Epoch 871 1.1444536447525024
Epoch 871 1.1199299097061157
Epoch 872 1.1327948570251465
Epoch 872 1.1408133506774902
Epoch 872 1.1328628063201904
Epoch 872 1.145615577697754
Epoch 872 1.1385362148284912
Epoch 872 1.1343443393707275
Epoch 872 1.1444536447525024
Epoch 872 1.1199300289154053
Epoch 873 1.1327948570251465
Epoch 873 1.1408131122589111
Epoch 873 1.13286292552948
Epoch 873 1.145615577697754
Epoch 873 1.1385363340377808
Epoch 873 1.1343443393707275
Epoch 873 1.1444536447525024
Epoch 873 1.1199300289154053
Epoch 874 1.1327950954437256
Epoch 874 1.1408132314682007
Epoch 874 1.13286292552948
Epoch 874 1.145615577697754
Epoch 874 1.1385363340377808
Epoch 874 1.1343443393707275
Epoch 874 1.1444536447525024
Epoch 874 1.1199301481246948
Epoch 875 1.132794737815857
Epoch 875 1.1408132314682007
Epoch 875 1.13286292552948
Epoch 875 1.145615577697754
Epoch 875 1.1385364532470703
Epoch 875 1.13434445858001

Epoch 907 1.1444536447525024
Epoch 907 1.119929313659668
Epoch 908 1.1327953338623047
Epoch 908 1.1408145427703857
Epoch 908 1.1328628063201904
Epoch 908 1.1456152200698853
Epoch 908 1.1385365724563599
Epoch 908 1.1343460083007812
Epoch 908 1.144453763961792
Epoch 908 1.1199291944503784
Epoch 909 1.1327952146530151
Epoch 909 1.1408145427703857
Epoch 909 1.1328630447387695
Epoch 909 1.1456152200698853
Epoch 909 1.1385365724563599
Epoch 909 1.1343458890914917
Epoch 909 1.144453763961792
Epoch 909 1.119929313659668
Epoch 910 1.1327950954437256
Epoch 910 1.1408145427703857
Epoch 910 1.13286292552948
Epoch 910 1.1456152200698853
Epoch 910 1.1385364532470703
Epoch 910 1.1343460083007812
Epoch 910 1.144453763961792
Epoch 910 1.119929313659668
Epoch 911 1.1327952146530151
Epoch 911 1.1408145427703857
Epoch 911 1.13286292552948
Epoch 911 1.1456149816513062
Epoch 911 1.1385364532470703
Epoch 911 1.1343458890914917
Epoch 911 1.144453763961792
Epoch 911 1.119929313659668
Epoch 912 1.13279521465301

Epoch 943 1.1343470811843872
Epoch 943 1.144453525543213
Epoch 943 1.1199287176132202
Epoch 944 1.1327952146530151
Epoch 944 1.1408156156539917
Epoch 944 1.1328635215759277
Epoch 944 1.1456148624420166
Epoch 944 1.1385365724563599
Epoch 944 1.1343472003936768
Epoch 944 1.1444536447525024
Epoch 944 1.1199285984039307
Epoch 945 1.1327953338623047
Epoch 945 1.1408156156539917
Epoch 945 1.1328636407852173
Epoch 945 1.1456146240234375
Epoch 945 1.1385363340377808
Epoch 945 1.1343472003936768
Epoch 945 1.1444536447525024
Epoch 945 1.1199287176132202
Epoch 946 1.1327952146530151
Epoch 946 1.1408156156539917
Epoch 946 1.1328636407852173
Epoch 946 1.145614743232727
Epoch 946 1.1385363340377808
Epoch 946 1.1343472003936768
Epoch 946 1.1444536447525024
Epoch 946 1.1199285984039307
Epoch 947 1.1327952146530151
Epoch 947 1.1408156156539917
Epoch 947 1.1328636407852173
Epoch 947 1.1456148624420166
Epoch 947 1.1385363340377808
Epoch 947 1.1343472003936768
Epoch 947 1.1444536447525024
Epoch 947 1.1199

Epoch 979 1.144453763961792
Epoch 979 1.119928240776062
Epoch 980 1.1327954530715942
Epoch 980 1.1408162117004395
Epoch 980 1.1328638792037964
Epoch 980 1.145614504814148
Epoch 980 1.1385365724563599
Epoch 980 1.134347915649414
Epoch 980 1.144453763961792
Epoch 980 1.119928240776062
Epoch 981 1.1327954530715942
Epoch 981 1.1408162117004395
Epoch 981 1.1328637599945068
Epoch 981 1.145614504814148
Epoch 981 1.1385364532470703
Epoch 981 1.1343480348587036
Epoch 981 1.144453763961792
Epoch 981 1.119928240776062
Epoch 982 1.1327954530715942
Epoch 982 1.1408162117004395
Epoch 982 1.1328638792037964
Epoch 982 1.145614504814148
Epoch 982 1.1385364532470703
Epoch 982 1.134347915649414
Epoch 982 1.144453763961792
Epoch 982 1.119928240776062
Epoch 983 1.1327954530715942
Epoch 983 1.14081609249115
Epoch 983 1.1328637599945068
Epoch 983 1.145614504814148
Epoch 983 1.1385364532470703
Epoch 983 1.1343480348587036
Epoch 983 1.144453763961792
Epoch 983 1.119928240776062
Epoch 984 1.1327954530715942
Epo